CREATE ROLE vireo WITH LOGIN PASSWORD 'vireo' CONNECTION LIMIT -1;
CREATE DATABASE vireo WITH OWNER = vireo ENCODING = 'UTF8' CONNECTION LIMIT = -1;
GRANT ALL PRIVILEGES ON DATABASE vireo TO vireo;
GRANT CONNECT ON DATABASE vireo TO vireo;